language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.1
env:
  matrix:
    - LARAVEL_VERSION=5.*
    - LARAVEL_VERSION=6.*
    - LARAVEL_VERSION=7.*
    - LARAVEL_VERSION=8.*
    - LARAVEL_VERSION=9.*

matrix:
  fast_finish: true

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source --no-suggest
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/framework:${LARAVEL_VERSION}" --no-update; fi;
  - composer update

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit
